### ISSUE TITLE
Code for int4

### ISSUE THREAD

**Issue by hoagy-davis-digges** [htqin/IR-QLoRA#1]
Thanks for sharing, I was wondering if you had the code you used to run the integer comparison with qa-lora?

**Comment by hoagy-davis-digges** [comment]
Also for integrating the IEC parameters into the LoRA adapters

**Comment by Xingyu-Zheng** [comment]
> Thanks for sharing, I was wondering if you had the code you used to run the integer comparison with qa-lora?

We are very honored by your interest in our work! We have improved the code for "IR-QLoRA with Integer Quantizer" in the latest submission. If you have any further questions, please feel free to contact us at any time.

**Comment by Xingyu-Zheng** [comment]
> Also for integrating the IEC parameters into the LoRA adapters

Thank you for your question. Here's an example of integrating the IEC parameters into the LoRA adapters:

Set $x\in \mathbb{R}^{1\times 4}, x' \in \mathbb{R}^{1\times 2} ,\ell_1 \in \mathbb{R}^{4\times 2}, \ell_2 \in \mathbb{R}^{2\times 4}$, $h=o=4$, $r=2$, 

$$
\begin{aligned}
x &= \begin{bmatrix}
 x_{11} & x_{12} & x_{13} & x_{14}
\end{bmatrix}  \\
\ell_1 &= \begin{bmatrix}
 \ell_{1_{11}} & \ell_{1_{12}} \\
 \ell_{1_{21}} & \ell_{1_{22}} \\
 \ell_{1_{31}} & \ell_{1_{32}} \\
 \ell_{1_{41}} & \ell_{1_{42}}
\end{bmatrix} \\
\ell_2 &= \begin{bmatrix}
 \ell_{2_{11}} & \ell_{2_{12}} & \ell_{2_{13}} & \ell_{2_{14}} \\
 \ell_{2_{21}} & \ell_{2_{22}} & \ell_{2_{23}} & \ell_{2_{24}} \\
\end{bmatrix} \\
\\
\end{aligned}
$$

The process of merging the IEC parameters into the LoRA for the given structure is as follows:：

<img width="762" alt="image" src="https://github.com/htqin/IR-QLoRA/assets/95268836/144b7e34-0d5b-4056-8b91-46fec68fb1d4">

For the structure in QA-LoRA, the process is similar. Please feel free to reach out if you have any questions about this.
